# Starter pipeline

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'Sonar'
    scannerMode: 'Other'
    extraProperties: 'sonar.projectKey=memer'
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    spotBugsAnalysis: false
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '${System.DefaultWorkingDirectory}/**/reports/jacoco/test/jacocoTestReport.xml'
    reportDirectory: '${System.DefaultWorkingDirectory}/**/reports/jacoco/test/html'
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'
- task: TomcatDeployment@1
  inputs:
    TomcatUrl: $(tomcatUrl)
    Username: '$(TOMCATUSERNAME)'
    Password: '$(TOMCATPASSWORD)'
    Warfile: 'build/libs/memer.war'
    Context: '/memer'
    ServerVersion: '7OrAbove'

