env:
  redisUri: ${REDIS_URI}
  botToken: ${BOT_TOKEN}
  memerUrl: ${MEMER_URL}
  dscViewerRedirectUrl: ${DSC_VIEWER_REDIRECT_URL}:""
  dscViewerUrl: ${DSC_VIEWER_URL}:""
  domain: ${DOMAIN:""}
  prod: ${TOMCAT_PROD:false}
  imageUploadedQueueName: ${IMAGE_UPLOADED_QUEUE_NAME}
  messageDeletedQueueName: ${MESSAGE_DELETED_QUEUE_NAME}
  channelUpdatedQueueName: ${CHANNEL_UPDATED_QUEUE_NAME}

